---
title: "Extremely Short Introduction for Ruby on Rails"
author: "Humberto C Marchezi"
date: "2008-12-26"
categories: [software-engineering]
---

Ruby on Rails
=============

<span style="font-size:85%;">This file contains brief descriptions of a
Ruby on Rails project.</span>

Important Rails Commands
------------------------

<span style="font-size:85%;">Here a list of the most relevant rails
command-line programs organized by task:</span>

-   <span style="font-size:85%;"><u>Starting a Rails Project:</u> <span
    style="text-decoration: none;">rails </span></span>

-   <span style="font-size:85%;"><u>Executing a Rails Project:</u><span
    style="text-decoration: none;"> ruby script\\server ( on application
    directory )</span></span>

-   <span style="font-size:85%;"><u>Generating a new Model:</u><span
    style="text-decoration: none;"> ruby script\\generate model
    </span></span>

-   <span style="font-size:85%;"><u>Generating a new
    Controller:</u><span style="text-decoration: none;"> ruby
    script\\generate controller </span></span>

  

Directory Contents
------------------

<span style="font-size:85%;"><u>**app**</u></span>

<span style="font-size:85%;">Holds all the code that's specific to this
particular application.</span>  

<span style="font-size:85%;"><u>**app/controllers**</u></span>

<span style="font-size:85%;">Holds controllers that should be named like
weblogs_controller.rb for automated URL mapping. All controllers should
descend from ApplicationController which itself descends from
ActionController::Base.</span>  

<span style="font-size:85%;"><u>**app/models**</u></span>

<span style="font-size:85%;">Holds models that should be named like
post.rb.</span>

<span style="font-size:85%;">Most models will descend from
ActiveRecord::Base.</span>  

<span style="font-size:85%;"><u>**app/views**</u></span>

<span style="font-size:85%;">Holds the template files for the view that
should be named like weblogs/index.erb for the WeblogsController\#index
action. All views use eRuby syntax.</span>  

<span style="font-size:85%;"><u>**app/views/layouts**</u></span>

<span style="font-size:85%;">Holds the template files for layouts to be
used with views. This models the common header/footer method of wrapping
views. In your views, define a layout using the `layout :default` and
create a file named default.erb. Inside default.erb, call \<% yield %\>
to render the view using this layout.</span>  

<span style="font-size:85%;"><u>**app/helpers**</u></span>

<span style="font-size:85%;">Holds view helpers that should be named
like weblogs_helper.rb. These are generated for you automatically when
using script/generate for controllers. Helpers can be used to wrap
functionality for your views into methods.</span>

<span style="font-size:85%;"><u>**config**</u></span>

<span style="font-size:85%;">Configuration files for the Rails
environment, the routing map, the database, and other
dependencies.</span>  

<span style="font-size:85%;"><u>**db**</u></span>

<span style="font-size:85%;">Contains the database schema in schema.rb.
db/migrate contains all the sequence of Migrations for your
schema.</span>  

<span style="font-size:85%;"><u>**doc**</u></span>

<span style="font-size:85%;">This directory is where your application
documentation will be stored when generated using
`rake doc:app`</span>  

<span style="font-size:85%;"><u>**lib**</u></span>

<span style="font-size:85%;">Application specific libraries. Basically,
any kind of custom code that doesn't belong under controllers, models,
or helpers. This directory is in the load path.</span>  

<span style="font-size:85%;"><u>**public**</u></span>

<span style="font-size:85%;">The directory available for the web server.
Contains subdirectories for images, stylesheets, and javascripts. Also
contains the dispatchers and the default HTML files. This should be set
as the DOCUMENT_ROOT of your web server.</span>  

<span style="font-size:85%;"><u>**script**</u></span>

<span style="font-size:85%;">Helper scripts for automation and
generation.</span>  

<span style="font-size:85%;">**test**</span>

<span style="font-size:85%;">Unit and functional tests along with
fixtures. When using the script/generate scripts, template test files
will be generated for you and placed in this directory.</span>  

<span style="font-size:85%;">**vendor**</span>

<span style="font-size:85%;">External libraries that the application
depends on. Also includes the plugins subdirectory. This directory is in
the load path.</span>  

How does Model, View and Controller relate to each other ?
----------------------------------------------------------

T<span style="font-size:85%;">he application directory is structured
like below:</span>

<span style="font-size:85%;">app</span>

<span style="font-size:85%;">\|-controllers</span>

<span style="font-size:85%;">\|-models</span>

<span style="font-size:85%;">\|-views</span>  
  

<span style="font-size:85%;">The fastest way to generate a complete crud
for a model is to generate a controller with the scaffold option:</span>

<span style="font-size:85%;">\> script/generate scaffold blog
title:string content:text date_created:datetime</span>  
  

<span style="font-size:85%;">After understanding of ruby-on-rails it is
considered better practice to generate models, views and controllers
separately:</span>

-   <span style="font-size:85%;">To generate a blog controller, one must
    type:</span>

<span style="font-size:85%;"> \> script/generate controller
blog</span>  

<span style="font-size:85%;"><span style="text-decoration: none;">
</span><u>Result:</u> a BlogController class will be generated at
app/controllers in BlogController.rb</span>  

-   <span style="font-size:85%;">To generate a blog model, one must
    type:</span>  

<span style="font-size:85%;"> \> script/generate model blog</span>  

<span style="font-size:85%;"> <u>Result</u>: a Blog class will be
generated at app/model in blog.rb</span>  

-   <span style="font-size:85%;">views can not be generated, you have to
    go to app/views/blog and create a blog.html.erb.</span>  

<span style="font-size:85%;">Views for BlogController are automatically
assigned in app/views/blog by name convention. ( Since
**Blog**Controller will have a **blog** directory in app/views
).</span>  

<span style="font-size:85%;">Views in app/views/blog, must have a
**\*.html.erb** extension and an **index.html.erb** must be created for
initial page. Other auxiliary pages can be created in the same directory
with different names.</span>  

<span style="font-size:85%;">In order to add/remove/update models
fields, one must only update the corresponding table in the data model
only. After that the following command should be executed to update the
models in Ruby-on-Rails:</span>

<span style="font-size:85%;">\> rake db:migrate</span>
