---
title: "Delphi for OO Programmers"
author: "Humberto C Marchezi"
date: "2006-11-09"
categories: [software-engineering]
---

I just came from a presentation about Borland products.  
One of the speakers were showing a piece of Delphi code to explain his
idea about object oriented programming and multi-tiered application for
Delphi.  
  
The Delphi syntax for declaring classes is very bad. Instead of using a
syntax similar to what we can find in C++, Java or C\# there were
strange reserved words. For declaring a Person class, one must code:  

    type Person = class
      private
        name : string;
      end;
    end;

  
To inherit from a Person it should be something like:  

    type SpecialPerson = class(Person)
      ......
    end;

  
After that in the beginning, the speaker said the "some people" say that
OO programming is about, for example, creating a Person class, adding
methods to manipulate data, using the instance to perform business logic
and then saving to the database. He said that is not the only way and
this is just the Java way to build OO systems.  
At this point I turned off my attention from the presentation for a
while and I started wondering if there are other ways to build OO
systems.  
  
What he was calling OO programming was a class with lots of static
methods responsible for executing a piece of the system. There was a
method for inserting a person, erasing a person, calculating a salary,
inserting a document, etc.  
  
Well I would say this is a Service Class but that doesn't mean that this
is a OO system. A lot of people say that because they have declared a
class or interface they can assume they are programming using the OO
paradigm. A paradigm is not only using objects but a way of thinking and
an object oriented system is one that was designed as a collection of
objects exchanging information between them by using methods.  
  
I have heard a lot of people saying that and it is almost rare to find
someone that really understans what OO means. At least here where I live
in Brazil. I don't think the programmers must know about OO paradigm but
they must admit when they don't know about a subject and should give the
adequate name to the methodology they are working with. In that case
above of the Delphi guy, I would say procedural paradigm.  
  
I also got to the conclusion that a programming language like Delphi was
not meant to use OO although it supports this paradigm.
