project:
  type: website
  output-dir: docs

website:
  title: "Mukeka & Tech"
  twitter-card: true
  open-graph: true
  cookie-consent: true

  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hcmarchezi

format:
  html:
    theme: darkly
    css: styles.css

comments:
  giscus: 
    repo: hcmarchezi/hcmarchezi.github.io

## include-after-body: footer.html
