project:
  type: website
  output-dir: docs

website:
  title: "Mukeka & Tech"
  twitter-card: true
  open-graph: true
  cookie-consent: true

  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hcmarchezi

format:
  html:
    theme: darkly
    css: styles.css
    grid:
      sidebar-width: 200px
      body-width:  1000px
      margin-width:  200px
      gutter-width : 1.5em

comments:
  giscus: 
    repo: hcmarchezi/hcmarchezi.github.io

## include-after-body: footer.html
